### ISSUE TITLE
loading non-embedded tilesheets?

### ISSUE THREAD

**Issue by kyeett** [lafriks/go-tiled#2]
Hi,

I found your library today, and it seems great. If I embedd the tilesheet in tile, it works fine, but can I do it without embedding?  
`
goroutine 1 [running]:
github.com/lafriks/go-tiled/render.(*Renderer).getTileImage(0xc000068840, 0xc0000f3b40, 0x0, 0x0, 0x0, 0x0)
	/Users/test/go/src/github.com/lafriks/go-tiled/render/renderer.go:86 +0x1c4
github.com/lafriks/go-tiled/render.(*Renderer).RenderLayer(0xc000068840, 0x0, 0xc0, 0xc000068840)
	/Users/test/go/src/github.com/lafriks/go-tiled/render/renderer.go:153 +0xe8
github.com/lafriks/go-tiled/render.(*Renderer).RenderVisibleLayers(0xc000068840, 0xc000068840, 0x0)
	/Users/test/go/src/github.com/lafriks/go-tiled/render/renderer.go:181 +0x79
main.run()
	/Users/test/go/src/github.com/kyeett/dungeon/main.go:34 +0x18d
main.main()
	/Users/test/go/src/github.com/kyeett/dungeon/main.go:51 +0x20
exit status 2
`

**Comment by lafriks** [comment]
Can you provide sample file?

**Comment by kyeett** [comment]
https://gist.github.com/kyeett/6f41304c9aa80f0367ea50c39e14eab7

Hi, sorry for the late reply! Here is an example. I'm not sure if this is a big problem, I think embedding the tileset into the map is the standard procedure, perhaps?

**Comment by lafriks** [comment]
Your provided sample is now rendered as:
![map](https://user-images.githubusercontent.com/165205/56638232-41f10780-6676-11e9-9009-248b75108383.png)

**Comment by kyeett** [comment]
Great, thanks!
