### ISSUE TITLE
Altering orthographic Renderer to expose the image

### ISSUE THREAD

**Issue by SolarLune** [lafriks/go-tiled#20]
Hello! 

I appreciate the framework that you made available for importing Tiled maps, and I appreciate the provided orthographic Renderer as well!

I was wondering, though, why the image itself isn't available for usage without saving it out to a file? It seems like it would be trivial to expose the Renderer's img property so that one could immediately use it (in my case, for a game)? If this is fine, I could make the change and send a PR.

Just wanted to get some insight as to the reason behind not making it available for this - thanks again, for your framework here!

**Comment by lafriks** [comment]
Thanks. I made rendering just for map previews but I see that it could have more use cases. Sure, PR is welcome.

**Comment by SolarLune** [comment]
Got it - submitted a PR, #21. Let me know if there's anything out of the ordinary about the approach I decided to go with. I thought it best to simply expose the image directly, as the other options didn't seem to be good ones. 

I could've made a function to return the Image directly, but that didn't make sense because it's a pointer; you could then modify the image by using the function to get the pointer. I also could've made a function to return a copy of the Image, but that seemed unnecessary, as direct usage with gamedev libraries (like Raylib-go or Ebiten) would probably have you make a second copy anyway to actually use it with the library (i.e. they don't take Image.NRGBA structs directly, but can convert them into another format that the library would take).

**Comment by lafriks** [comment]
Fixed by #21

**Comment by SolarLune** [comment]
Thanks!
