### ISSUE TITLE
Create branch release/v0.3.0

### ISSUE THREAD

**Issue by MetalBlueberry** [lafriks/go-tiled#32]
It would be nice to have the branch release/v0.3.0 so we can merge the breaking pull request into it.

Maybe we can establish some functional requirements to reach v0.3.0, or just a time limit.

**Comment by MetalBlueberry** [comment]
The point is that I have a branch feature/save_load_tileset that I would like to send, but it depends on feature/parse_colors. Having the branch release/v0.3.0 will allow me to send the merge request so we can keep moving.

thank you!

**Comment by lafriks** [comment]
I don't think we need new branch. I could merge that PR but it needs that default value fixed imho

**Comment by MetalBlueberry** [comment]
I missed that comment, done!
