### ISSUE TITLE
Object Visibility Not Taking Default Values

### ISSUE THREAD

**Issue by Qwarkster** [lafriks/go-tiled#37]
From what I can gleam from the source, despite the fact that the fields in the struct denote default values, they don't seem to be implemented on Objects yet.

I notice that the Unmarshal methods tend to be where the defaults are set, and I don't see that implemented for the Object at this point. Thus, any values written into the TMX file show up, but when something is set to the Tiled default, it doesn't write it to the TMX file. The visible property is the most noticeable one, but I am sure there are others.

I presume implementing that aspect similar to the other items would help this to actually behave as expected.

This is probably similar to another task to review default values, provided the appropriate Unmarshal method is put in place and used.

**Comment by lafriks** [comment]
Yeah, default value handling should be re-evaluted
