### ISSUE TITLE
Outdated documentation?

### ISSUE THREAD

**Issue by fr3fou** [lafriks/go-tiled#40]
Looking at the documentation for `tiled.Layer`,
```go
	// This is the attribute you'd like to use, not Data. Tile entry at (x,y) is obtained using l.DecodedTiles[y*map.Width+x].
	Tiles []*LayerTile
```
we are instructed to use `l.DecodedTiles` which doesn't exist on the `tiled.Layer` struct. What Is the intended way to access the actual decoded tiles?

**Comment by Qwarkster** [comment]
I *think* it's a typo on the comment and instead of DecodedTiles, it's Tiles. Thus l.Tiles[y*map.Width+x] gets what you want. Yes, just went back and checked some of my old code, that is definitely the issue.
