### ISSUE TITLE
Possible width and height swapped?

### ISSUE THREAD

**Issue by jabolopes** [lafriks/go-tiled#44]
Hi,

Thanks a lot for this library. I was wondering if in the following LOC:
  https://github.com/lafriks/go-tiled/blob/v0.3.0/tmx_layer.go#L238

TileWidth and TileHeight are swapped? Perhaps it should be the following?
  return l.OffsetX + x*l._map.TileWidth, l.OffsetY + y*l._map.TileHeight

Thanks,
Jose

**Comment by MetalBlueberry** [comment]
I think you may be right. Maybe anyone noticed before because most of the tiles are squared. Maybe you can submit a pull request to change it.
