### ISSUE TITLE
The game panics when having too much tile sets,

### ISSUE THREAD

**Issue by lehangajanayake** [lafriks/go-tiled#45]
if .tmx has tile ids beyond 1000s the program panic with nil pointer diff

**Comment by lafriks** [comment]
Where exactly does it panics? Can you post stack trace?

**Comment by lehangajanayake** [comment]
here is the full [code](https://drive.google.com/drive/folders/1buzoEWObqyExYuKAAiyAGNM9WB6MMDDL?usp=sharing) run it and you will see the err. I'm not certain that this is a problem with the lib but I thought it'll be good to share it with you. Please check it out. (I have a map that panic and a one that does not.)

**Comment by lafriks** [comment]
Can you give name of the map that panics?

**Comment by lehangajanayake** [comment]
I think it's untitled.tmx anyway the map that uses the Base_chip_pipo.png tileset is the one that panics

**Comment by sailormoon** [comment]
I verified there was an issue running this with go-tiled@v0.3.0 in the repo:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1005dc154]

goroutine 1 [running]:
github.com/lafriks/go-tiled/render.(*Renderer).RenderLayer(0x1400007b080, 0x0)
	/Users/me/go/pkg/mod/github.com/lafriks/go-tiled@v0.3.0/render/renderer.go:165 +0x2f4
main.main()
	/Users/me/Downloads/go-tiled_issue/main.go:41 +0x278
exit status 2
```

however, updating the `go.mod`, the issue is gone. I would suggest  updating your version @lehangajanayake and post back here if the issue still persists. Until then, I think this is safe to mark closed.
