### ISSUE TITLE
Error when loading from embedded FS

### ISSUE THREAD

**Issue by christopher-kleine** [lafriks/go-tiled#57]
Hi!

I can't seem to load from embedded storage.
The folder structure looks like this:
```
assets
|
|
|__ images
|  |
|  |__ world.png
| 
|__ maps
|  |
|  |__ level1.tmx
|
|__ tilesets
   |
   |__ world.tsx
```

`level1.tmx` refers to `../tilesets/world.tsx` and `world.tsx` refers to `../images/world.png`.
The assets are embedded using Go 1.16 Embed syntax:

```go
//go:embed assets/*
var assets embed.FS
```

I can load files just fine using `assets` methods. According to the documentation (and the source-code), the regular "LoadFromFile" method uses a nil-loader. A nil-loader uses the default `os`-Loader.

Alternative should be, to use a custom `Loader`. And then use it to load the map.

```go
loader := tiled.Loader{FileSystem: http.FS(assets)}

f, err := assets.Open("assets/maps/" + filename)
if err != nil {
	log.Fatal(err)
}

level, err = loader.LoadFromReader("", f)
if err != nil {
	log.Fatal(err)
}
```

This results in `open assets\tilesets\world.tsx: file does not exist`.
Loading the map using `LoadFromFile` instead, manages to find the tileset. But not the image used *in* the tileset.

The situation is even worse in this case, as it tries to load from the absolute path:
`open C:\Users\Chris\Projects\TMXDemo\assets\maps\assets\tilesets\world.tsx: file does 
not exist`.

Embedding the tileset into the map however works like a charm.

Any ideas how to fix this?

**Comment by lafriks** [comment]
Could you create sample project with embeded files to reproduce issue more easily?
