### ISSUE TITLE
Failed to parse TSX files with WangSet and WangColor tile ID equal to -1

### ISSUE THREAD

**Issue by jabolopes** [lafriks/go-tiled#65]
Hi,

I am seeing some parse errors in go-tiled v0.9.0. I believe this is the result of PR https://github.com/lafriks/go-tiled/pull/55.

How to reproduce: I created a super basic tileset using Tiled 1.9.1 with a terrain (aka wangset). This is the final file:

```
<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.1" name="TEST" tilewidth="32" tileheight="32" tilecount="3600" columns="60">
 <image source="samplemap.png" width="1920" height="1920"/>
 <wangsets>
  <wangset name="Unnamed Set" type="corner" tile="-1">
   <wangcolor name="" color="#ff0000" tile="-1" probability="1"/>
  </wangset>
 </wangsets>
</tileset>
```

Tiled is using `-1` in the `tile` attribute of both `wangset` and `wangcolor`. I thought `-1` was an invalid value for the `tile` attribute, but I looked into the source code for Tiled and the wangset `imageTileId` is an `int` (not a `uint32`) and it defaults to `-1`:
https://github.com/mapeditor/tiled/blob/6ad9e7136fedc80940819ab44a7b55bffa6b8beb/src/libtiled/wangset.h#L241

Likewise, the wangcolor `imageId` is also an `int` (not a `uint32`) and it defaults to `-1`:
https://github.com/mapeditor/tiled/blob/6ad9e7136fedc80940819ab44a7b55bffa6b8beb/src/libtiled/wangset.h#L185

When I try to parse the tsx file above with go-tiled v0.9.0, it fails with the following error:
```strconv.ParseUint: parsing "-1": invalid syntax```

I believe what happens is that go-tiled is trying to parse the `-1` into a `uint32` (e.g., the WangSet.TileID field) and it fails for this reason.

I suspect that the `Wangset.TileID` and the `Wangcolor.TileID` should be `int` instead of `uint32`. Perhaps there are other `TileID` that should also be `int` but I didn't check.

What do you think?

Thanks,
Jose

**Comment by jabolopes** [comment]
I prepared the following patch as a workaround to my loading problem:
https://github.com/lafriks/go-tiled/commit/80cbf4078986761c94a39bda6ccb5939eb2c44a3

Let me know if this patch would be useful for this issue or not.

Thanks,
Jose

**Comment by lafriks** [comment]
Maybe changing to int64 would be better but yes please submit PR

**Comment by jabolopes** [comment]
Done in https://github.com/lafriks/go-tiled/pull/66. Thanks!
